version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prabhjot
      POSTGRES_PASSWORD: shyftlabs
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
